# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epoch', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('time_period', models.DurationField()),
                ('duration', models.DurationField()),
                ('type', models.PositiveSmallIntegerField()),
                ('errand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Errand')),
            ],
        ),
    ]
