# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errand',
            old_name='about',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='about',
            new_name='description',
        ),
    ]
